// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datacollector.proto

package datacollector

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/goserver/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadSpec struct {
	MeasureKey           string   `protobuf:"bytes,1,opt,name=measure_key,json=measureKey,proto3" json:"measure_key,omitempty"`
	JobName              string   `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSpec) Reset()         { *m = ReadSpec{} }
func (m *ReadSpec) String() string { return proto.CompactTextString(m) }
func (*ReadSpec) ProtoMessage()    {}
func (*ReadSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{0}
}

func (m *ReadSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSpec.Unmarshal(m, b)
}
func (m *ReadSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSpec.Marshal(b, m, deterministic)
}
func (m *ReadSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSpec.Merge(m, src)
}
func (m *ReadSpec) XXX_Size() int {
	return xxx_messageInfo_ReadSpec.Size(m)
}
func (m *ReadSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSpec proto.InternalMessageInfo

func (m *ReadSpec) GetMeasureKey() string {
	if m != nil {
		return m.MeasureKey
	}
	return ""
}

func (m *ReadSpec) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *ReadSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReadConfig struct {
	Spec                 []*ReadSpec `protobuf:"bytes,1,rep,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadConfig) Reset()         { *m = ReadConfig{} }
func (m *ReadConfig) String() string { return proto.CompactTextString(m) }
func (*ReadConfig) ProtoMessage()    {}
func (*ReadConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{1}
}

func (m *ReadConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadConfig.Unmarshal(m, b)
}
func (m *ReadConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadConfig.Marshal(b, m, deterministic)
}
func (m *ReadConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadConfig.Merge(m, src)
}
func (m *ReadConfig) XXX_Size() int {
	return xxx_messageInfo_ReadConfig.Size(m)
}
func (m *ReadConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ReadConfig proto.InternalMessageInfo

func (m *ReadConfig) GetSpec() []*ReadSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type Config struct {
	Data                 []*DataSet `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{2}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetData() []*DataSet {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reading struct {
	Timestamp            int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Measure              *proto1.State `protobuf:"bytes,2,opt,name=measure,proto3" json:"measure,omitempty"`
	Collapsed            bool          `protobuf:"varint,3,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Reading) Reset()         { *m = Reading{} }
func (m *Reading) String() string { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()    {}
func (*Reading) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{3}
}

func (m *Reading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reading.Unmarshal(m, b)
}
func (m *Reading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reading.Marshal(b, m, deterministic)
}
func (m *Reading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reading.Merge(m, src)
}
func (m *Reading) XXX_Size() int {
	return xxx_messageInfo_Reading.Size(m)
}
func (m *Reading) XXX_DiscardUnknown() {
	xxx_messageInfo_Reading.DiscardUnknown(m)
}

var xxx_messageInfo_Reading proto.InternalMessageInfo

func (m *Reading) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Reading) GetMeasure() *proto1.State {
	if m != nil {
		return m.Measure
	}
	return nil
}

func (m *Reading) GetCollapsed() bool {
	if m != nil {
		return m.Collapsed
	}
	return false
}

type DataSet struct {
	JobName              string     `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Identifier           string     `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Readings             []*Reading `protobuf:"bytes,3,rep,name=readings,proto3" json:"readings,omitempty"`
	Staging              []*Reading `protobuf:"bytes,5,rep,name=staging,proto3" json:"staging,omitempty"`
	SpecName             string     `protobuf:"bytes,4,opt,name=spec_name,json=specName,proto3" json:"spec_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{4}
}

func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (m *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(m, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *DataSet) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *DataSet) GetReadings() []*Reading {
	if m != nil {
		return m.Readings
	}
	return nil
}

func (m *DataSet) GetStaging() []*Reading {
	if m != nil {
		return m.Staging
	}
	return nil
}

func (m *DataSet) GetSpecName() string {
	if m != nil {
		return m.SpecName
	}
	return ""
}

type GetDataSetsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataSetsRequest) Reset()         { *m = GetDataSetsRequest{} }
func (m *GetDataSetsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataSetsRequest) ProtoMessage()    {}
func (*GetDataSetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{5}
}

func (m *GetDataSetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataSetsRequest.Unmarshal(m, b)
}
func (m *GetDataSetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataSetsRequest.Marshal(b, m, deterministic)
}
func (m *GetDataSetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataSetsRequest.Merge(m, src)
}
func (m *GetDataSetsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataSetsRequest.Size(m)
}
func (m *GetDataSetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataSetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataSetsRequest proto.InternalMessageInfo

type GetDataSetsResponse struct {
	DataSets             []*DataSet `protobuf:"bytes,1,rep,name=data_sets,json=dataSets,proto3" json:"data_sets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetDataSetsResponse) Reset()         { *m = GetDataSetsResponse{} }
func (m *GetDataSetsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataSetsResponse) ProtoMessage()    {}
func (*GetDataSetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{6}
}

func (m *GetDataSetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataSetsResponse.Unmarshal(m, b)
}
func (m *GetDataSetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataSetsResponse.Marshal(b, m, deterministic)
}
func (m *GetDataSetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataSetsResponse.Merge(m, src)
}
func (m *GetDataSetsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataSetsResponse.Size(m)
}
func (m *GetDataSetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataSetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataSetsResponse proto.InternalMessageInfo

func (m *GetDataSetsResponse) GetDataSets() []*DataSet {
	if m != nil {
		return m.DataSets
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadSpec)(nil), "datacollector.ReadSpec")
	proto.RegisterType((*ReadConfig)(nil), "datacollector.ReadConfig")
	proto.RegisterType((*Config)(nil), "datacollector.Config")
	proto.RegisterType((*Reading)(nil), "datacollector.Reading")
	proto.RegisterType((*DataSet)(nil), "datacollector.DataSet")
	proto.RegisterType((*GetDataSetsRequest)(nil), "datacollector.GetDataSetsRequest")
	proto.RegisterType((*GetDataSetsResponse)(nil), "datacollector.GetDataSetsResponse")
}

func init() { proto.RegisterFile("datacollector.proto", fileDescriptor_feee553d97ffd8f9) }

var fileDescriptor_feee553d97ffd8f9 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd4, 0x30,
	0x10, 0x85, 0x09, 0xbb, 0x34, 0xd9, 0x59, 0x21, 0x24, 0xb7, 0x82, 0x50, 0x10, 0x14, 0x9f, 0x0a,
	0x48, 0x59, 0x94, 0xe5, 0xc2, 0xb9, 0x48, 0x48, 0x20, 0x71, 0x70, 0x24, 0x0e, 0x5c, 0x56, 0x4e,
	0x32, 0x4d, 0x5d, 0x36, 0x71, 0xb0, 0x67, 0x2b, 0xf5, 0x17, 0xf2, 0xb7, 0x90, 0x1d, 0x87, 0x36,
	0x05, 0x2d, 0xb7, 0xe4, 0xf3, 0x7b, 0xe3, 0xf7, 0x26, 0x81, 0xc3, 0x5a, 0x92, 0xac, 0xf4, 0x76,
	0x8b, 0x15, 0x69, 0x93, 0xf5, 0x46, 0x93, 0x66, 0x0f, 0x27, 0xf0, 0x78, 0xdd, 0x28, 0xba, 0xd8,
	0x95, 0x59, 0xa5, 0xdb, 0x55, 0x69, 0x34, 0x5d, 0xa0, 0xd9, 0xea, 0x46, 0x55, 0xab, 0x46, 0x5b,
	0x34, 0x57, 0x68, 0x56, 0xde, 0xb6, 0x1a, 0x5e, 0x86, 0x19, 0xfc, 0x3b, 0x24, 0x02, 0x65, 0x5d,
	0xf4, 0x58, 0xb1, 0x97, 0xb0, 0x6c, 0x51, 0xda, 0x9d, 0xc1, 0xcd, 0x0f, 0xbc, 0x4e, 0xa3, 0x93,
	0xe8, 0x74, 0x21, 0x20, 0xa0, 0x2f, 0x78, 0xcd, 0x9e, 0x42, 0x72, 0xa9, 0xcb, 0x4d, 0x27, 0x5b,
	0x4c, 0xef, 0xfb, 0xd3, 0xf8, 0x52, 0x97, 0x5f, 0x65, 0x8b, 0x8c, 0xc1, 0xdc, 0xe3, 0x99, 0xc7,
	0xfe, 0x99, 0x7f, 0x00, 0x70, 0xb3, 0xcf, 0x74, 0x77, 0xae, 0x1a, 0xf6, 0x16, 0xe6, 0xb6, 0xc7,
	0x2a, 0x8d, 0x4e, 0x66, 0xa7, 0xcb, 0xfc, 0x49, 0x36, 0x6d, 0x34, 0x86, 0x10, 0x5e, 0xc4, 0xdf,
	0xc3, 0x41, 0xb0, 0xbd, 0x81, 0xb9, 0x53, 0x06, 0xdb, 0xe3, 0x3b, 0xb6, 0x8f, 0x92, 0x64, 0x81,
	0x24, 0xbc, 0x86, 0xf7, 0x10, 0xbb, 0x39, 0xaa, 0x6b, 0xd8, 0x73, 0x58, 0x90, 0x6a, 0xd1, 0x92,
	0x6c, 0x7b, 0xdf, 0x64, 0x26, 0x6e, 0x00, 0x7b, 0x0d, 0x71, 0xa8, 0xe5, 0x7b, 0x2c, 0xf3, 0x47,
	0xd9, 0xb8, 0xa4, 0xac, 0x20, 0x49, 0x28, 0xc6, 0x73, 0x37, 0xc8, 0x5d, 0x27, 0x7b, 0x8b, 0xb5,
	0x6f, 0x97, 0x88, 0x1b, 0xc0, 0x7f, 0x45, 0x10, 0x87, 0x0c, 0x93, 0xed, 0x44, 0xd3, 0xed, 0xbc,
	0x00, 0x50, 0x35, 0x76, 0xa4, 0xce, 0x15, 0x9a, 0xb0, 0xba, 0x5b, 0x84, 0xe5, 0x90, 0x98, 0x21,
	0xb8, 0x4d, 0x67, 0xff, 0x2c, 0x1a, 0x7a, 0x89, 0x3f, 0x3a, 0xf6, 0x0e, 0x62, 0x4b, 0xb2, 0x51,
	0x5d, 0x93, 0x3e, 0xd8, 0x6b, 0x19, 0x65, 0xec, 0x19, 0x2c, 0xdc, 0x72, 0x87, 0x84, 0x73, 0x1f,
	0x22, 0x71, 0xc0, 0x45, 0xe4, 0x47, 0xc0, 0x3e, 0x21, 0x85, 0x2e, 0x56, 0xe0, 0xcf, 0x1d, 0x5a,
	0xe2, 0x9f, 0xe1, 0x70, 0x42, 0x6d, 0xaf, 0x3b, 0x8b, 0x6c, 0x0d, 0x0b, 0x77, 0xd7, 0xc6, 0x22,
	0xd9, 0xff, 0x7c, 0x99, 0xa4, 0x0e, 0xe6, 0xbc, 0x83, 0x23, 0x07, 0xcf, 0x46, 0x49, 0x81, 0xe6,
	0x4a, 0x55, 0xc8, 0xbe, 0xc1, 0xf2, 0xd6, 0x1d, 0xec, 0xd5, 0x9d, 0x41, 0x7f, 0xa7, 0x3a, 0xe6,
	0xfb, 0x24, 0x43, 0x44, 0x7e, 0xaf, 0x3c, 0xf0, 0x7f, 0xf8, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9b, 0xa9, 0xb3, 0xda, 0x3c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataCollectorServiceClient is the client API for DataCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataCollectorServiceClient interface {
	GetDataSets(ctx context.Context, in *GetDataSetsRequest, opts ...grpc.CallOption) (*GetDataSetsResponse, error)
}

type dataCollectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataCollectorServiceClient(cc *grpc.ClientConn) DataCollectorServiceClient {
	return &dataCollectorServiceClient{cc}
}

func (c *dataCollectorServiceClient) GetDataSets(ctx context.Context, in *GetDataSetsRequest, opts ...grpc.CallOption) (*GetDataSetsResponse, error) {
	out := new(GetDataSetsResponse)
	err := c.cc.Invoke(ctx, "/datacollector.DataCollectorService/GetDataSets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCollectorServiceServer is the server API for DataCollectorService service.
type DataCollectorServiceServer interface {
	GetDataSets(context.Context, *GetDataSetsRequest) (*GetDataSetsResponse, error)
}

func RegisterDataCollectorServiceServer(s *grpc.Server, srv DataCollectorServiceServer) {
	s.RegisterService(&_DataCollectorService_serviceDesc, srv)
}

func _DataCollectorService_GetDataSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCollectorServiceServer).GetDataSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacollector.DataCollectorService/GetDataSets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCollectorServiceServer).GetDataSets(ctx, req.(*GetDataSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataCollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datacollector.DataCollectorService",
	HandlerType: (*DataCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataSets",
			Handler:    _DataCollectorService_GetDataSets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datacollector.proto",
}
