// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datacollector.proto

package datacollector

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/goserver/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Reading struct {
	Timestamp            int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Measure              *proto1.State `protobuf:"bytes,2,opt,name=measure,proto3" json:"measure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Reading) Reset()         { *m = Reading{} }
func (m *Reading) String() string { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()    {}
func (*Reading) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{0}
}
func (m *Reading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reading.Unmarshal(m, b)
}
func (m *Reading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reading.Marshal(b, m, deterministic)
}
func (m *Reading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reading.Merge(m, src)
}
func (m *Reading) XXX_Size() int {
	return xxx_messageInfo_Reading.Size(m)
}
func (m *Reading) XXX_DiscardUnknown() {
	xxx_messageInfo_Reading.DiscardUnknown(m)
}

var xxx_messageInfo_Reading proto.InternalMessageInfo

func (m *Reading) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Reading) GetMeasure() *proto1.State {
	if m != nil {
		return m.Measure
	}
	return nil
}

type DataSet struct {
	JobName              string     `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Identifier           string     `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Readings             []*Reading `protobuf:"bytes,3,rep,name=readings,proto3" json:"readings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_feee553d97ffd8f9, []int{1}
}
func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (m *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(m, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *DataSet) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *DataSet) GetReadings() []*Reading {
	if m != nil {
		return m.Readings
	}
	return nil
}

func init() {
	proto.RegisterType((*Reading)(nil), "datacollector.Reading")
	proto.RegisterType((*DataSet)(nil), "datacollector.DataSet")
}

func init() { proto.RegisterFile("datacollector.proto", fileDescriptor_feee553d97ffd8f9) }

var fileDescriptor_feee553d97ffd8f9 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x51, 0x4b, 0xc3, 0x40,
	0x0c, 0xc7, 0xa9, 0x05, 0xbb, 0x66, 0x88, 0x70, 0x82, 0x54, 0x11, 0x29, 0x7b, 0xaa, 0x2f, 0x57,
	0xe8, 0xbe, 0x82, 0xcf, 0x3e, 0xdc, 0x3e, 0x80, 0xe4, 0xda, 0xd8, 0xdd, 0xe8, 0x35, 0x23, 0xcd,
	0xc4, 0x8f, 0x2f, 0xb4, 0x4e, 0xdd, 0x63, 0x7e, 0x49, 0x7e, 0xfc, 0x13, 0xb8, 0xeb, 0x50, 0xb1,
	0xe5, 0x61, 0xa0, 0x56, 0x59, 0xec, 0x51, 0x58, 0xd9, 0xdc, 0x5c, 0xc0, 0xc7, 0x6d, 0x1f, 0x74,
	0x7f, 0xf2, 0xb6, 0xe5, 0x58, 0x7b, 0x61, 0xdd, 0x93, 0x0c, 0xdc, 0x87, 0xb6, 0xee, 0x79, 0x22,
	0xf9, 0x24, 0xa9, 0xe7, 0xb5, 0x7a, 0x29, 0x16, 0xc7, 0xc6, 0x41, 0xe6, 0x08, 0xbb, 0x30, 0xf6,
	0xe6, 0x09, 0x72, 0x0d, 0x91, 0x26, 0xc5, 0x78, 0x2c, 0x92, 0x32, 0xa9, 0x52, 0xf7, 0x07, 0xcc,
	0x0b, 0x64, 0x91, 0x70, 0x3a, 0x09, 0x15, 0x57, 0x65, 0x52, 0xad, 0x9b, 0x5b, 0x7b, 0xf6, 0xda,
	0x9d, 0xa2, 0x92, 0x3b, 0xf7, 0x37, 0x5f, 0x90, 0xbd, 0xa2, 0xe2, 0x8e, 0xd4, 0x3c, 0xc0, 0xea,
	0xc0, 0xfe, 0x7d, 0xc4, 0x48, 0xb3, 0x32, 0x77, 0xd9, 0x81, 0xfd, 0x1b, 0x46, 0x32, 0xcf, 0x00,
	0xa1, 0xa3, 0x51, 0xc3, 0x47, 0x20, 0x99, 0x9d, 0xb9, 0xfb, 0x47, 0x4c, 0x03, 0x2b, 0x59, 0x92,
	0x4d, 0x45, 0x5a, 0xa6, 0xd5, 0xba, 0xb9, 0xb7, 0x97, 0x5f, 0xf8, 0x09, 0xee, 0x7e, 0xe7, 0xfc,
	0xf5, 0x7c, 0xd4, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xa5, 0x36, 0xee, 0x2f, 0x01, 0x00,
	0x00,
}
